# Generated by Django 2.2.7 on 2019-11-09 19:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.TextField(max_length=100)),
                ('imagenA', models.ImageField(blank=True, upload_to='pictures/actor')),
            ],
            options={
                'verbose_name': 'Actor',
                'verbose_name_plural': 'Actores',
                'ordering': ['nombres'],
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('Direccion', models.CharField(max_length=220)),
                ('TipoServicio', models.CharField(max_length=100)),
                ('PrecioBoleto', models.TextField()),
                ('Distrito', models.TextField(max_length=100)),
                ('ImagenL', models.ImageField(blank=True, upload_to='pictures/local')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.TextField(max_length=50)),
                ('total', models.TextField(max_length=50)),
                ('funcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Local')),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(max_length=100)),
                ('trailer', models.TextField(max_length=100)),
                ('categoria', models.TextField(max_length=100)),
                ('genero', models.TextField(max_length=100)),
                ('imagenP', models.ImageField(blank=True, upload_to='pictures/pelicula')),
                ('sinopsis', models.TextField(max_length=100)),
                ('director', models.TextField(max_length=100)),
                ('idioma', models.TextField(max_length=100)),
                ('actor', models.ManyToManyField(to='cinema.Actor')),
            ],
            options={
                'verbose_name': 'Pelicula',
                'verbose_name_plural': 'Peliculas',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Sala', models.TextField(max_length=50)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Local')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Pelicula')),
            ],
            options={
                'verbose_name': 'Funcion',
                'verbose_name_plural': 'Funciones',
                'ordering': ['local'],
            },
        ),
    ]
